[package]
name = "owner_owned"
version = "1.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ckb-std = "0.14.1"

[features]
devnet = []
testnet = []
mainnet = []
