# [rust]
# # path of rust contracts workspace directory,
# # a `Cargo.toml` file is expected under the directory.
# workspace_dir = "."

# capsule version
version = "0.10.3"

[[contracts]]
name = "ickb_logic"
template_type = "Rust"

[[contracts]]
name = "limit_order"
template_type = "Rust"
