[workspace]
members = ["tests","contracts/ickb-owner-lock", "contracts/ickb-deposit-lock","contracts/ickb-receipt"]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = false
codegen-units = 1
panic = 'abort'
