[workspace]
members = ["tests","contracts/domain_logic","contracts/owner_owned","contracts/limit_order","contracts/utils"]
exclude = ["tests"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
