[workspace]
members = ["tests","contracts/ickb_domain_logic","contracts/ckb_sudt_limit_order","contracts/ckb_utils"]

[profile.release]
overflow-checks = true
opt-level = 's'
lto = false
codegen-units = 1
panic = 'abort'
