[[cells]]
name = "ICKB_LOGIC"
enable_type_id = true 
location = { file = "../../build/release/ickb_logic" }

[[cells]]
name = "LIMIT_ORDER"
enable_type_id = true 
location = { file = "../../build/release/limit_order" }

[[cells]]
name = "OWNED_OWNER"
enable_type_id = true 
location = { file = "../../build/release/owned_owner" }


[[cells]]
name = "XUDT"
enable_type_id = false
location = { file = "../../build/release/xudt" }


# Genesis scripts deployments, see:
# https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0024-ckb-genesis-script-list/0024-ckb-genesis-script-list.md
[[cells]]
name = "SECP256K1_BLAKE160"
enable_type_id = false
location = { tx_hash = "${genesis_tx_hash}", index = 1 }

[[cells]]
name = "DAO"
enable_type_id = false
location = { tx_hash = "${genesis_tx_hash}", index = 2 }

[[cells]]
name = "SECP256K1_DATA"
enable_type_id = false
location = { tx_hash = "${genesis_tx_hash}", index = 3 }

[[cells]]
name = "SECP256K1_BLAKE160_MULTISIG"
enable_type_id = false
location = { tx_hash = "${genesis_tx_hash}", index = 4 }
 
# Dep group cells
[[dep_groups]]
name = "ickb_dep_group"
cells = [
  "ICKB_LOGIC",
  "LIMIT_ORDER",
  "OWNED_OWNER",
  "XUDT",
  "SECP256K1_BLAKE160",
  "DAO",
  "SECP256K1_DATA",
  "SECP256K1_BLAKE160_MULTISIG",
]

# The lock script set to output cells
[lock]
code_hash = "${secp256k1_blake160_code_hash}"
args = "${account_lock_args}"
hash_type = "type"
