[[cells]]
name = "ICKB_LOGIC"
enable_type_id = true 
location = { file = "../../build/release/ickb_logic" }

[[cells]]
name = "LIMIT_ORDER"
enable_type_id = true 
location = { file = "../../build/release/limit_order" }

[[cells]]
name = "OWNED_OWNER"
enable_type_id = true 
location = { file = "../../build/release/owned_owner" }


# xUDT deployment, see:
# https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0052-extensible-udt/0052-extensible-udt.md
[[cells]]
name = "XUDT"
enable_type_id = false
location = { tx_hash = "0xc07844ce21b38e4b071dd0e1ee3b0e27afd8d7532491327f39b786343f558ab7", index = 0 }


# Genesis scripts deployments, see:
# https://github.com/nervosnetwork/rfcs/blob/master/rfcs/0024-ckb-genesis-script-list/0024-ckb-genesis-script-list.md
[[cells]]
name = "SECP256K1_BLAKE160"
enable_type_id = false
location = { tx_hash = "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c", index = 1 }

[[cells]]
name = "DAO"
enable_type_id = false
location = { tx_hash = "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c", index = 2 }

[[cells]]
name = "SECP256K1_DATA"
enable_type_id = false
location = { tx_hash = "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c", index = 3 }

[[cells]]
name = "SECP256K1_BLAKE160_MULTISIG"
enable_type_id = false
location = { tx_hash = "0xe2fb199810d49a4d8beec56718ba2593b665db9d52299a0f9e6e75416d73ff5c", index = 4 }
 
# Dep group cells
[[dep_groups]]
name = "ickb_dep_group"
cells = [
  "ICKB_LOGIC",
  "LIMIT_ORDER",
  "OWNED_OWNER",
  "XUDT",
  "SECP256K1_BLAKE160",
  "DAO",
  "SECP256K1_DATA",
  "SECP256K1_BLAKE160_MULTISIG"
]

# TODO
# The lock script set to output cells
# code_hash = "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8"
# args = "0x0000000000000000000000000000000000000000"
# hash_type = "type"
