[workspace]
members = ["tests", "contracts/ickb_logic", "contracts/owned_owner", "contracts/limit_order"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
